service: vitalmeds-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: prod
  memorySize: 256
  timeout: 15
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
      Resource: "arn:aws:s3:::corevitalmeds-kyc-vault/*"
  environment:
    MONGO_URI: mongodb+srv://vitalmedsAI_admin:Amarfiku456@vital-ai.24kpznh.mongodb.net/vitalmeds?appName=Vital-AI
    COGNITO_USER_POOL_ID: ap-south-1_t7cmqYdPT
    COGNITO_CLIENT_ID: 2gomoic0dpgtimj3dg8tfjqceu
    AWS_S3_BUCKET: corevitalmeds-kyc-vault
    S3_BUCKET_NAME: corevitalmeds-kyc-vault # ✨ Added for bulletproof variable matching

functions:
  api:
    handler: server.handler
    events:
      - httpApi:
          path: '/{proxy+}'
          method: '*'